---
- hosts: all
  become: yes
  vars:
    daemons:
      - vault
      - consul
      - nomad
  tasks:
    - name: Running prestart books
      include: "{{ item }}"
<<<<<<< HEAD:ansible/start_hashistack.yml
      with_fileglob: "/vagrant/playbooks/prestart/*"
=======
      with_fileglob: "prestart/*"
>>>>>>> 942ad3a3f09478d50d69c12645b6f175c76b0a20:ansible/playbooks/start_hashistack.yml

    - name: "Start hashistack"
      systemd: name={{item}} state=started
      loop: "{{ daemons }}"

    - name: Wait for consul to start
      uri:
        url: http://127.0.0.1:8500/ui/dc1/services
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1

    - name: Wait for nomad to start
      uri:
        url: http://127.0.0.1:4646/v1/jobs
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1

    - name: Wait for vault to start
      uri:
        url: http://127.0.0.1:8200/ui/
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1

    - name: Running poststart books
      include: "{{ item }}"
<<<<<<< HEAD:ansible/start_hashistack.yml
      with_fileglob: "/vagrant/playbooks/poststart/*"
=======
      with_fileglob: "poststart/*"
>>>>>>> 942ad3a3f09478d50d69c12645b6f175c76b0a20:ansible/playbooks/start_hashistack.yml
