---
- hosts: all
  become: yes
  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes

    - name: Install unzip
      apt: pkg=unzip state=latest

    - name: Install ansible galaxy roles
      command: "ansible-galaxy install {{ item }} -p /etc/ansible/roles/"
      loop: "{{ ansible.galaxy.roles }}"

    - name: Install docker
      include_role:
        name: geerlingguy.docker

    - name: "install systemd unit file"
      template: src={{item}}.service.j2 dest=/etc/systemd/system/{{item}}.service
      loop: "{{ hashicorp.daemons }}"

    - name: "create /etc/{{item}}.d"
      file:
        path: /etc/{{item}}.d
        state: directory
      loop: "{{ hashicorp.daemons }}"

    - name: "add config.json"
      template: src={{item}}.hcl.j2 dest=/etc/{{item}}.d/config.hcl
      loop: "{{ hashicorp.daemons }}"

    - name: "start"
      systemd: state=started name={{item}} daemon_reload=yes
      loop: "{{ hashicorp.daemons }}"

    - name: Install hashistack
      include_role:
        name: hashistack
      vars:
        software: "{{ item.key }}"
        version: "{{ item.value }}"
      loop: "{{ query('dict', hashicorp.tools) }}"

    - name: Add hashistack version announcment to motd
      copy:
        dest: "/etc/update-motd.d/99-hashistack"
        mode: "+rx"
        content: |
          #!/bin/sh
          echo "Hashistack versions:"
          echo "Consul:\t\t$(consul -version)"
          echo "Vault:\t\t$(vault -version)"
          echo "Terraform:\t$(terraform -version)"
          echo "Nomad:\t\t$(nomad -version)"
          echo "Packer:\t\t$(packer -version)\n"

    - name: CNI - Ensure Dir
      file:
        path: /opt/cni/bin
        state: directory

    - name: CNI - Install
      unarchive:
        src: https://github.com/containernetworking/plugins/releases/download/v0.8.4/cni-plugins-linux-amd64-v0.8.4.tgz
        remote_src: true
        dest: /opt/cni/bin

    - name: CNI - Tune iptables - persist
      copy:
        dest: "/etc/sysctl.d/cni-iptables"
        mode: "+rx"
        content: |
          net.bridge.bridge-nf-call-arptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1

    - name: CNI - Tune iptables - run
      command: sysctl --system