name: Build vagrantbox

on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    # Macos includes virtualbox and vagrant.
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs make build
      - name: Run make build
        run: make build
