name: Build

on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    # Macos includes virtualbox and vagrant.
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Show versions
      - name: Versions on runner
        run: make versions

      # Runs make build
      - name: Run make build
        run: make build

      - name: Make box avaiable as artifact
        uses: actions/upload-artifact@v2
        with:
          name: vagrantbox
          path: packer/output-hashistack/package.box
  test:
    needs: build
    # Macos includes virtualbox and vagrant.
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: vagrantbox
          path: packer/output-hashistack

      - name: Display structure of downloaded files
        run: ls -R packer/output-hashistack

      # Runs make test
      - name: Run make test
        run: make test
